import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import arrow from "../icons/arrow.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ganesh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ipng" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <section className={`${styles.section} ${styles.herosec}`}>
            <div className={styles.grid2x}>
              <div className={styles.profileblock}>
                {/* <div className={styles.profileimage}></div> */}
                <div>
                  <div className={styles.title}>Ganesh</div>
                  <div className={styles.pro}>Data Scientist, Researcher.</div>
                </div>
              </div>
              <div className={styles.biocon}>
                <div className={styles.bio}>
                  Hi, I am Ganesh. I am a Data Scientist and Reseacher. I have 3
                  years of experience in the field. Previously worked at
                  Sagacious Research and Waycool Technologies. Currently
                  pursuing masters in Business Intelligence from Wichita
                  State University.
                </div>
                <Link href="/about">
                  <div className={styles.link}>
                    Learn more{" "}
                    <span>
                      {" "}
                      <Image
                        src={arrow}
                        width="12"
                        height="12"
                        alt="G"
                        className={styles.arrow}
                      />
                    </span>{" "}
                  </div>
                </Link>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
